// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gjallarhorn/v1/gjallarhorn.proto

package gjallarhornv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GjallarhornService_Send_FullMethodName            = "/gjallarhorn.v1.GjallarhornService/Send"
	GjallarhornService_GetNotification_FullMethodName = "/gjallarhorn.v1.GjallarhornService/GetNotification"
)

// GjallarhornServiceClient is the client API for GjallarhornService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GjallarhornService delivers notifications over one or more channels and exposes
// the delivery status of a previously sent notification.
type GjallarhornServiceClient interface {
	// Send queues and dispatches a notification, returning its final state.
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	// GetNotification returns a notification and its current delivery status.
	GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*GetNotificationResponse, error)
}

type gjallarhornServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGjallarhornServiceClient(cc grpc.ClientConnInterface) GjallarhornServiceClient {
	return &gjallarhornServiceClient{cc}
}

func (c *gjallarhornServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, GjallarhornService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gjallarhornServiceClient) GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*GetNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotificationResponse)
	err := c.cc.Invoke(ctx, GjallarhornService_GetNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GjallarhornServiceServer is the server API for GjallarhornService service.
// All implementations should embed UnimplementedGjallarhornServiceServer
// for forward compatibility.
//
// GjallarhornService delivers notifications over one or more channels and exposes
// the delivery status of a previously sent notification.
type GjallarhornServiceServer interface {
	// Send queues and dispatches a notification, returning its final state.
	Send(context.Context, *SendRequest) (*SendResponse, error)
	// GetNotification returns a notification and its current delivery status.
	GetNotification(context.Context, *GetNotificationRequest) (*GetNotificationResponse, error)
}

// UnimplementedGjallarhornServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGjallarhornServiceServer struct{}

func (UnimplementedGjallarhornServiceServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedGjallarhornServiceServer) GetNotification(context.Context, *GetNotificationRequest) (*GetNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotification not implemented")
}
func (UnimplementedGjallarhornServiceServer) testEmbeddedByValue() {}

// UnsafeGjallarhornServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GjallarhornServiceServer will
// result in compilation errors.
type UnsafeGjallarhornServiceServer interface {
	mustEmbedUnimplementedGjallarhornServiceServer()
}

func RegisterGjallarhornServiceServer(s grpc.ServiceRegistrar, srv GjallarhornServiceServer) {
	// If the following call panics, it indicates UnimplementedGjallarhornServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GjallarhornService_ServiceDesc, srv)
}

func _GjallarhornService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GjallarhornServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GjallarhornService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GjallarhornServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GjallarhornService_GetNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GjallarhornServiceServer).GetNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GjallarhornService_GetNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GjallarhornServiceServer).GetNotification(ctx, req.(*GetNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GjallarhornService_ServiceDesc is the grpc.ServiceDesc for GjallarhornService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GjallarhornService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gjallarhorn.v1.GjallarhornService",
	HandlerType: (*GjallarhornServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _GjallarhornService_Send_Handler,
		},
		{
			MethodName: "GetNotification",
			Handler:    _GjallarhornService_GetNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gjallarhorn/v1/gjallarhorn.proto",
}
