// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gjallarhorn/v1/gjallarhorn.proto

package gjallarhornv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notification is one message addressed to a recipient over a channel.
type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the server-assigned UUID of the notification.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// realm_id is the optional tenant the notification belongs to.
	RealmId string `protobuf:"bytes,2,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	// recipient is the channel-specific address (e.g. an email address).
	Recipient string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// channel selects the delivery transport (e.g. EMAIL).
	Channel string `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	// template names an optional message template (rendered in a later wave).
	Template string `protobuf:"bytes,5,opt,name=template,proto3" json:"template,omitempty"`
	// data carries structured values for template rendering.
	Data *structpb.Struct `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// subject is the rendered message subject.
	Subject string `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	// body is the rendered message body.
	Body string `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	// status is the delivery lifecycle state.
	Status string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	// last_error holds the most recent delivery error, if any.
	LastError string `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// created_at is when the notification was queued.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is when the notification last changed state.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_gjallarhorn_v1_gjallarhorn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_gjallarhorn_v1_gjallarhorn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_gjallarhorn_v1_gjallarhorn_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *Notification) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Notification) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Notification) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Notification) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Notification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Notification) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SendRequest carries the notification to deliver. id and status are
// server-assigned.
type SendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// realm_id is the optional tenant the notification belongs to.
	RealmId string `protobuf:"bytes,1,opt,name=realm_id,json=realmId,proto3" json:"realm_id,omitempty"`
	// recipient is the channel-specific address (required).
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// channel selects the delivery transport (required).
	Channel string `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	// template names an optional message template.
	Template string `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`
	// data carries structured values for template rendering.
	Data *structpb.Struct `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	// subject is the message subject.
	Subject string `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	// body is the message body.
	Body          string `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_gjallarhorn_v1_gjallarhorn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gjallarhorn_v1_gjallarhorn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_gjallarhorn_v1_gjallarhorn_proto_rawDescGZIP(), []int{1}
}

func (x *SendRequest) GetRealmId() string {
	if x != nil {
		return x.RealmId
	}
	return ""
}

func (x *SendRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SendRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SendRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// SendResponse returns the notification after a delivery attempt.
type SendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// notification is the persisted notification with its delivery status.
	Notification  *Notification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_gjallarhorn_v1_gjallarhorn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gjallarhorn_v1_gjallarhorn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_gjallarhorn_v1_gjallarhorn_proto_rawDescGZIP(), []int{2}
}

func (x *SendResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

// GetNotificationRequest selects a notification by id.
type GetNotificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the UUID of the notification to fetch.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_gjallarhorn_v1_gjallarhorn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gjallarhorn_v1_gjallarhorn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_gjallarhorn_v1_gjallarhorn_proto_rawDescGZIP(), []int{3}
}

func (x *GetNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetNotificationResponse carries the requested notification.
type GetNotificationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// notification is the requested notification with its delivery status.
	Notification  *Notification `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationResponse) Reset() {
	*x = GetNotificationResponse{}
	mi := &file_gjallarhorn_v1_gjallarhorn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationResponse) ProtoMessage() {}

func (x *GetNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gjallarhorn_v1_gjallarhorn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return file_gjallarhorn_v1_gjallarhorn_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

var File_gjallarhorn_v1_gjallarhorn_proto protoreflect.FileDescriptor

const file_gjallarhorn_v1_gjallarhorn_proto_rawDesc = "" +
	"\n" +
	" gjallarhorn/v1/gjallarhorn.proto\x12\x0egjallarhorn.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x03\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\brealm_id\x18\x02 \x01(\tR\arealmId\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x1a\n" +
	"\btemplate\x18\x05 \x01(\tR\btemplate\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd7\x01\n" +
	"\vSendRequest\x12\x19\n" +
	"\brealm_id\x18\x01 \x01(\tR\arealmId\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1a\n" +
	"\btemplate\x18\x04 \x01(\tR\btemplate\x12+\n" +
	"\x04data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\"P\n" +
	"\fSendResponse\x12@\n" +
	"\fnotification\x18\x01 \x01(\v2\x1c.gjallarhorn.v1.NotificationR\fnotification\"(\n" +
	"\x16GetNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x17GetNotificationResponse\x12@\n" +
	"\fnotification\x18\x01 \x01(\v2\x1c.gjallarhorn.v1.NotificationR\fnotification2\xbb\x01\n" +
	"\x12GjallarhornService\x12A\n" +
	"\x04Send\x12\x1b.gjallarhorn.v1.SendRequest\x1a\x1c.gjallarhorn.v1.SendResponse\x12b\n" +
	"\x0fGetNotification\x12&.gjallarhorn.v1.GetNotificationRequest\x1a'.gjallarhorn.v1.GetNotificationResponseB\xce\x01\n" +
	"\x12com.gjallarhorn.v1B\x10GjallarhornProtoP\x01ZMgithub.com/fromforgesoftware/gjallarhorn/pkg/api/gjallarhorn/v1;gjallarhornv1\xa2\x02\x03GXX\xaa\x02\x0eGjallarhorn.V1\xca\x02\x0eGjallarhorn\\V1\xe2\x02\x1aGjallarhorn\\V1\\GPBMetadata\xea\x02\x0fGjallarhorn::V1b\x06proto3"

var (
	file_gjallarhorn_v1_gjallarhorn_proto_rawDescOnce sync.Once
	file_gjallarhorn_v1_gjallarhorn_proto_rawDescData []byte
)

func file_gjallarhorn_v1_gjallarhorn_proto_rawDescGZIP() []byte {
	file_gjallarhorn_v1_gjallarhorn_proto_rawDescOnce.Do(func() {
		file_gjallarhorn_v1_gjallarhorn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gjallarhorn_v1_gjallarhorn_proto_rawDesc), len(file_gjallarhorn_v1_gjallarhorn_proto_rawDesc)))
	})
	return file_gjallarhorn_v1_gjallarhorn_proto_rawDescData
}

var file_gjallarhorn_v1_gjallarhorn_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gjallarhorn_v1_gjallarhorn_proto_goTypes = []any{
	(*Notification)(nil),            // 0: gjallarhorn.v1.Notification
	(*SendRequest)(nil),             // 1: gjallarhorn.v1.SendRequest
	(*SendResponse)(nil),            // 2: gjallarhorn.v1.SendResponse
	(*GetNotificationRequest)(nil),  // 3: gjallarhorn.v1.GetNotificationRequest
	(*GetNotificationResponse)(nil), // 4: gjallarhorn.v1.GetNotificationResponse
	(*structpb.Struct)(nil),         // 5: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_gjallarhorn_v1_gjallarhorn_proto_depIdxs = []int32{
	5, // 0: gjallarhorn.v1.Notification.data:type_name -> google.protobuf.Struct
	6, // 1: gjallarhorn.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	6, // 2: gjallarhorn.v1.Notification.updated_at:type_name -> google.protobuf.Timestamp
	5, // 3: gjallarhorn.v1.SendRequest.data:type_name -> google.protobuf.Struct
	0, // 4: gjallarhorn.v1.SendResponse.notification:type_name -> gjallarhorn.v1.Notification
	0, // 5: gjallarhorn.v1.GetNotificationResponse.notification:type_name -> gjallarhorn.v1.Notification
	1, // 6: gjallarhorn.v1.GjallarhornService.Send:input_type -> gjallarhorn.v1.SendRequest
	3, // 7: gjallarhorn.v1.GjallarhornService.GetNotification:input_type -> gjallarhorn.v1.GetNotificationRequest
	2, // 8: gjallarhorn.v1.GjallarhornService.Send:output_type -> gjallarhorn.v1.SendResponse
	4, // 9: gjallarhorn.v1.GjallarhornService.GetNotification:output_type -> gjallarhorn.v1.GetNotificationResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gjallarhorn_v1_gjallarhorn_proto_init() }
func file_gjallarhorn_v1_gjallarhorn_proto_init() {
	if File_gjallarhorn_v1_gjallarhorn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gjallarhorn_v1_gjallarhorn_proto_rawDesc), len(file_gjallarhorn_v1_gjallarhorn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gjallarhorn_v1_gjallarhorn_proto_goTypes,
		DependencyIndexes: file_gjallarhorn_v1_gjallarhorn_proto_depIdxs,
		MessageInfos:      file_gjallarhorn_v1_gjallarhorn_proto_msgTypes,
	}.Build()
	File_gjallarhorn_v1_gjallarhorn_proto = out.File
	file_gjallarhorn_v1_gjallarhorn_proto_goTypes = nil
	file_gjallarhorn_v1_gjallarhorn_proto_depIdxs = nil
}
