// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/gjallarhorn/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ChannelSender is an autogenerated mock type for the ChannelSender type
type ChannelSender struct {
	mock.Mock
}

type ChannelSender_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelSender) EXPECT() *ChannelSender_Expecter {
	return &ChannelSender_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function with no fields
func (_m *ChannelSender) Channel() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ChannelSender_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type ChannelSender_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
func (_e *ChannelSender_Expecter) Channel() *ChannelSender_Channel_Call {
	return &ChannelSender_Channel_Call{Call: _e.mock.On("Channel")}
}

func (_c *ChannelSender_Channel_Call) Run(run func()) *ChannelSender_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChannelSender_Channel_Call) Return(_a0 string) *ChannelSender_Channel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelSender_Channel_Call) RunAndReturn(run func() string) *ChannelSender_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, n
func (_m *ChannelSender) Send(ctx context.Context, n domain.Notification) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type ChannelSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - n domain.Notification
func (_e *ChannelSender_Expecter) Send(ctx interface{}, n interface{}) *ChannelSender_Send_Call {
	return &ChannelSender_Send_Call{Call: _e.mock.On("Send", ctx, n)}
}

func (_c *ChannelSender_Send_Call) Run(run func(ctx context.Context, n domain.Notification)) *ChannelSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Notification))
	})
	return _c
}

func (_c *ChannelSender_Send_Call) Return(_a0 error) *ChannelSender_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelSender_Send_Call) RunAndReturn(run func(context.Context, domain.Notification) error) *ChannelSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannelSender creates a new instance of ChannelSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelSender {
	mock := &ChannelSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
