// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/gjallarhorn/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// DeliveryAttemptRepository is an autogenerated mock type for the DeliveryAttemptRepository type
type DeliveryAttemptRepository struct {
	mock.Mock
}

type DeliveryAttemptRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DeliveryAttemptRepository) EXPECT() *DeliveryAttemptRepository_Expecter {
	return &DeliveryAttemptRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *DeliveryAttemptRepository) Create(_a0 context.Context, _a1 domain.DeliveryAttempt) (domain.DeliveryAttempt, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.DeliveryAttempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.DeliveryAttempt) (domain.DeliveryAttempt, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.DeliveryAttempt) domain.DeliveryAttempt); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.DeliveryAttempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.DeliveryAttempt) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeliveryAttemptRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DeliveryAttemptRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.DeliveryAttempt
func (_e *DeliveryAttemptRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *DeliveryAttemptRepository_Create_Call {
	return &DeliveryAttemptRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *DeliveryAttemptRepository_Create_Call) Run(run func(_a0 context.Context, _a1 domain.DeliveryAttempt)) *DeliveryAttemptRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.DeliveryAttempt))
	})
	return _c
}

func (_c *DeliveryAttemptRepository_Create_Call) Return(_a0 domain.DeliveryAttempt, _a1 error) *DeliveryAttemptRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeliveryAttemptRepository_Create_Call) RunAndReturn(run func(context.Context, domain.DeliveryAttempt) (domain.DeliveryAttempt, error)) *DeliveryAttemptRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByNotification provides a mock function with given fields: ctx, notificationID
func (_m *DeliveryAttemptRepository) ListByNotification(ctx context.Context, notificationID string) ([]domain.DeliveryAttempt, error) {
	ret := _m.Called(ctx, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for ListByNotification")
	}

	var r0 []domain.DeliveryAttempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.DeliveryAttempt, error)); ok {
		return rf(ctx, notificationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.DeliveryAttempt); ok {
		r0 = rf(ctx, notificationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeliveryAttempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, notificationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeliveryAttemptRepository_ListByNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByNotification'
type DeliveryAttemptRepository_ListByNotification_Call struct {
	*mock.Call
}

// ListByNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationID string
func (_e *DeliveryAttemptRepository_Expecter) ListByNotification(ctx interface{}, notificationID interface{}) *DeliveryAttemptRepository_ListByNotification_Call {
	return &DeliveryAttemptRepository_ListByNotification_Call{Call: _e.mock.On("ListByNotification", ctx, notificationID)}
}

func (_c *DeliveryAttemptRepository_ListByNotification_Call) Run(run func(ctx context.Context, notificationID string)) *DeliveryAttemptRepository_ListByNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DeliveryAttemptRepository_ListByNotification_Call) Return(_a0 []domain.DeliveryAttempt, _a1 error) *DeliveryAttemptRepository_ListByNotification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeliveryAttemptRepository_ListByNotification_Call) RunAndReturn(run func(context.Context, string) ([]domain.DeliveryAttempt, error)) *DeliveryAttemptRepository_ListByNotification_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeliveryAttemptRepository creates a new instance of DeliveryAttemptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeliveryAttemptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeliveryAttemptRepository {
	mock := &DeliveryAttemptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
