// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// NotificationPreferenceRepository is an autogenerated mock type for the NotificationPreferenceRepository type
type NotificationPreferenceRepository struct {
	mock.Mock
}

type NotificationPreferenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationPreferenceRepository) EXPECT() *NotificationPreferenceRepository_Expecter {
	return &NotificationPreferenceRepository_Expecter{mock: &_m.Mock}
}

// IsSuppressed provides a mock function with given fields: ctx, realmID, recipient, channel
func (_m *NotificationPreferenceRepository) IsSuppressed(ctx context.Context, realmID string, recipient string, channel string) (bool, error) {
	ret := _m.Called(ctx, realmID, recipient, channel)

	if len(ret) == 0 {
		panic("no return value specified for IsSuppressed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, realmID, recipient, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, realmID, recipient, channel)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, realmID, recipient, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationPreferenceRepository_IsSuppressed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSuppressed'
type NotificationPreferenceRepository_IsSuppressed_Call struct {
	*mock.Call
}

// IsSuppressed is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
//   - recipient string
//   - channel string
func (_e *NotificationPreferenceRepository_Expecter) IsSuppressed(ctx interface{}, realmID interface{}, recipient interface{}, channel interface{}) *NotificationPreferenceRepository_IsSuppressed_Call {
	return &NotificationPreferenceRepository_IsSuppressed_Call{Call: _e.mock.On("IsSuppressed", ctx, realmID, recipient, channel)}
}

func (_c *NotificationPreferenceRepository_IsSuppressed_Call) Run(run func(ctx context.Context, realmID string, recipient string, channel string)) *NotificationPreferenceRepository_IsSuppressed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *NotificationPreferenceRepository_IsSuppressed_Call) Return(_a0 bool, _a1 error) *NotificationPreferenceRepository_IsSuppressed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationPreferenceRepository_IsSuppressed_Call) RunAndReturn(run func(context.Context, string, string, string) (bool, error)) *NotificationPreferenceRepository_IsSuppressed_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, realmID, recipient, channel, suppressed
func (_m *NotificationPreferenceRepository) Set(ctx context.Context, realmID string, recipient string, channel string, suppressed bool) error {
	ret := _m.Called(ctx, realmID, recipient, channel, suppressed)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) error); ok {
		r0 = rf(ctx, realmID, recipient, channel, suppressed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationPreferenceRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type NotificationPreferenceRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
//   - recipient string
//   - channel string
//   - suppressed bool
func (_e *NotificationPreferenceRepository_Expecter) Set(ctx interface{}, realmID interface{}, recipient interface{}, channel interface{}, suppressed interface{}) *NotificationPreferenceRepository_Set_Call {
	return &NotificationPreferenceRepository_Set_Call{Call: _e.mock.On("Set", ctx, realmID, recipient, channel, suppressed)}
}

func (_c *NotificationPreferenceRepository_Set_Call) Run(run func(ctx context.Context, realmID string, recipient string, channel string, suppressed bool)) *NotificationPreferenceRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *NotificationPreferenceRepository_Set_Call) Return(_a0 error) *NotificationPreferenceRepository_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationPreferenceRepository_Set_Call) RunAndReturn(run func(context.Context, string, string, string, bool) error) *NotificationPreferenceRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationPreferenceRepository creates a new instance of NotificationPreferenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationPreferenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationPreferenceRepository {
	mock := &NotificationPreferenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
