// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/gjallarhorn/internal/domain"
	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"

	time "time"
)

// NotificationUsecase is an autogenerated mock type for the NotificationUsecase type
type NotificationUsecase struct {
	mock.Mock
}

type NotificationUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationUsecase) EXPECT() *NotificationUsecase_Expecter {
	return &NotificationUsecase_Expecter{mock: &_m.Mock}
}

// DispatchDue provides a mock function with given fields: ctx, limit
func (_m *NotificationUsecase) DispatchDue(ctx context.Context, limit int) (int, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for DispatchDue")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, limit)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationUsecase_DispatchDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchDue'
type NotificationUsecase_DispatchDue_Call struct {
	*mock.Call
}

// DispatchDue is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *NotificationUsecase_Expecter) DispatchDue(ctx interface{}, limit interface{}) *NotificationUsecase_DispatchDue_Call {
	return &NotificationUsecase_DispatchDue_Call{Call: _e.mock.On("DispatchDue", ctx, limit)}
}

func (_c *NotificationUsecase_DispatchDue_Call) Run(run func(ctx context.Context, limit int)) *NotificationUsecase_DispatchDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *NotificationUsecase_DispatchDue_Call) Return(_a0 int, _a1 error) *NotificationUsecase_DispatchDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationUsecase_DispatchDue_Call) RunAndReturn(run func(context.Context, int) (int, error)) *NotificationUsecase_DispatchDue_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *NotificationUsecase) Get(ctx context.Context, opts ...search.Option) (domain.Notification, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Notification, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Notification); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type NotificationUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *NotificationUsecase_Expecter) Get(ctx interface{}, opts ...interface{}) *NotificationUsecase_Get_Call {
	return &NotificationUsecase_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *NotificationUsecase_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *NotificationUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *NotificationUsecase_Get_Call) Return(_a0 domain.Notification, _a1 error) *NotificationUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationUsecase_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Notification, error)) *NotificationUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *NotificationUsecase) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.Notification], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.Notification]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.Notification], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.Notification]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.Notification])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type NotificationUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *NotificationUsecase_Expecter) List(ctx interface{}, opts ...interface{}) *NotificationUsecase_List_Call {
	return &NotificationUsecase_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *NotificationUsecase_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *NotificationUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *NotificationUsecase_List_Call) Return(_a0 resource.ListResponse[domain.Notification], _a1 error) *NotificationUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationUsecase_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.Notification], error)) *NotificationUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Schedule provides a mock function with given fields: ctx, n, at
func (_m *NotificationUsecase) Schedule(ctx context.Context, n domain.Notification, at time.Time) (domain.Notification, error) {
	ret := _m.Called(ctx, n, at)

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Notification, time.Time) (domain.Notification, error)); ok {
		return rf(ctx, n, at)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Notification, time.Time) domain.Notification); ok {
		r0 = rf(ctx, n, at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Notification, time.Time) error); ok {
		r1 = rf(ctx, n, at)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationUsecase_Schedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schedule'
type NotificationUsecase_Schedule_Call struct {
	*mock.Call
}

// Schedule is a helper method to define mock.On call
//   - ctx context.Context
//   - n domain.Notification
//   - at time.Time
func (_e *NotificationUsecase_Expecter) Schedule(ctx interface{}, n interface{}, at interface{}) *NotificationUsecase_Schedule_Call {
	return &NotificationUsecase_Schedule_Call{Call: _e.mock.On("Schedule", ctx, n, at)}
}

func (_c *NotificationUsecase_Schedule_Call) Run(run func(ctx context.Context, n domain.Notification, at time.Time)) *NotificationUsecase_Schedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Notification), args[2].(time.Time))
	})
	return _c
}

func (_c *NotificationUsecase_Schedule_Call) Return(_a0 domain.Notification, _a1 error) *NotificationUsecase_Schedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationUsecase_Schedule_Call) RunAndReturn(run func(context.Context, domain.Notification, time.Time) (domain.Notification, error)) *NotificationUsecase_Schedule_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, n
func (_m *NotificationUsecase) Send(ctx context.Context, n domain.Notification) (domain.Notification, error) {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Notification) (domain.Notification, error)); ok {
		return rf(ctx, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Notification) domain.Notification); ok {
		r0 = rf(ctx, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Notification) error); ok {
		r1 = rf(ctx, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationUsecase_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type NotificationUsecase_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - n domain.Notification
func (_e *NotificationUsecase_Expecter) Send(ctx interface{}, n interface{}) *NotificationUsecase_Send_Call {
	return &NotificationUsecase_Send_Call{Call: _e.mock.On("Send", ctx, n)}
}

func (_c *NotificationUsecase_Send_Call) Run(run func(ctx context.Context, n domain.Notification)) *NotificationUsecase_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Notification))
	})
	return _c
}

func (_c *NotificationUsecase_Send_Call) Return(_a0 domain.Notification, _a1 error) *NotificationUsecase_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationUsecase_Send_Call) RunAndReturn(run func(context.Context, domain.Notification) (domain.Notification, error)) *NotificationUsecase_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationUsecase creates a new instance of NotificationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationUsecase {
	mock := &NotificationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
