// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/gjallarhorn/internal/domain"
	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"

	time "time"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

type NotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationRepository) EXPECT() *NotificationRepository_Expecter {
	return &NotificationRepository_Expecter{mock: &_m.Mock}
}

// ClaimDue provides a mock function with given fields: ctx, now, limit
func (_m *NotificationRepository) ClaimDue(ctx context.Context, now time.Time, limit int) ([]domain.Notification, error) {
	ret := _m.Called(ctx, now, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimDue")
	}

	var r0 []domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]domain.Notification, error)); ok {
		return rf(ctx, now, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []domain.Notification); ok {
		r0 = rf(ctx, now, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, now, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationRepository_ClaimDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimDue'
type NotificationRepository_ClaimDue_Call struct {
	*mock.Call
}

// ClaimDue is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
//   - limit int
func (_e *NotificationRepository_Expecter) ClaimDue(ctx interface{}, now interface{}, limit interface{}) *NotificationRepository_ClaimDue_Call {
	return &NotificationRepository_ClaimDue_Call{Call: _e.mock.On("ClaimDue", ctx, now, limit)}
}

func (_c *NotificationRepository_ClaimDue_Call) Run(run func(ctx context.Context, now time.Time, limit int)) *NotificationRepository_ClaimDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(int))
	})
	return _c
}

func (_c *NotificationRepository_ClaimDue_Call) Return(_a0 []domain.Notification, _a1 error) *NotificationRepository_ClaimDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationRepository_ClaimDue_Call) RunAndReturn(run func(context.Context, time.Time, int) ([]domain.Notification, error)) *NotificationRepository_ClaimDue_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *NotificationRepository) Create(_a0 context.Context, _a1 domain.Notification) (domain.Notification, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Notification) (domain.Notification, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Notification) domain.Notification); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Notification) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NotificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.Notification
func (_e *NotificationRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *NotificationRepository_Create_Call {
	return &NotificationRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *NotificationRepository_Create_Call) Run(run func(_a0 context.Context, _a1 domain.Notification)) *NotificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Notification))
	})
	return _c
}

func (_c *NotificationRepository_Create_Call) Return(_a0 domain.Notification, _a1 error) *NotificationRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Notification) (domain.Notification, error)) *NotificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *NotificationRepository) Get(ctx context.Context, opts ...search.Option) (domain.Notification, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.Notification, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.Notification); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type NotificationRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *NotificationRepository_Expecter) Get(ctx interface{}, opts ...interface{}) *NotificationRepository_Get_Call {
	return &NotificationRepository_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *NotificationRepository_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *NotificationRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *NotificationRepository_Get_Call) Return(_a0 domain.Notification, _a1 error) *NotificationRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationRepository_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.Notification, error)) *NotificationRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *NotificationRepository) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.Notification], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.Notification]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.Notification], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.Notification]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.Notification])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type NotificationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *NotificationRepository_Expecter) List(ctx interface{}, opts ...interface{}) *NotificationRepository_List_Call {
	return &NotificationRepository_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *NotificationRepository_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *NotificationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *NotificationRepository_List_Call) Return(_a0 resource.ListResponse[domain.Notification], _a1 error) *NotificationRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationRepository_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.Notification], error)) *NotificationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, lastErr
func (_m *NotificationRepository) UpdateStatus(ctx context.Context, id string, status domain.NotificationStatus, lastErr string) error {
	ret := _m.Called(ctx, id, status, lastErr)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.NotificationStatus, string) error); ok {
		r0 = rf(ctx, id, status, lastErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type NotificationRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status domain.NotificationStatus
//   - lastErr string
func (_e *NotificationRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, lastErr interface{}) *NotificationRepository_UpdateStatus_Call {
	return &NotificationRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, lastErr)}
}

func (_c *NotificationRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status domain.NotificationStatus, lastErr string)) *NotificationRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.NotificationStatus), args[3].(string))
	})
	return _c
}

func (_c *NotificationRepository_UpdateStatus_Call) Return(_a0 error) *NotificationRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, domain.NotificationStatus, string) error) *NotificationRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
