// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/gjallarhorn/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/fromforgesoftware/go-kit/application/repository"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// NotificationTemplateRepository is an autogenerated mock type for the NotificationTemplateRepository type
type NotificationTemplateRepository struct {
	mock.Mock
}

type NotificationTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationTemplateRepository) EXPECT() *NotificationTemplateRepository_Expecter {
	return &NotificationTemplateRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *NotificationTemplateRepository) Create(_a0 context.Context, _a1 domain.NotificationTemplate) (domain.NotificationTemplate, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.NotificationTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.NotificationTemplate) (domain.NotificationTemplate, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.NotificationTemplate) domain.NotificationTemplate); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.NotificationTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.NotificationTemplate) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationTemplateRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type NotificationTemplateRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 domain.NotificationTemplate
func (_e *NotificationTemplateRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *NotificationTemplateRepository_Create_Call {
	return &NotificationTemplateRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *NotificationTemplateRepository_Create_Call) Run(run func(_a0 context.Context, _a1 domain.NotificationTemplate)) *NotificationTemplateRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.NotificationTemplate))
	})
	return _c
}

func (_c *NotificationTemplateRepository_Create_Call) Return(_a0 domain.NotificationTemplate, _a1 error) *NotificationTemplateRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationTemplateRepository_Create_Call) RunAndReturn(run func(context.Context, domain.NotificationTemplate) (domain.NotificationTemplate, error)) *NotificationTemplateRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, delType, opts
func (_m *NotificationTemplateRepository) Delete(ctx context.Context, delType repository.DeleteType, opts ...search.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, delType)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteType, ...search.Option) error); ok {
		r0 = rf(ctx, delType, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationTemplateRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type NotificationTemplateRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - delType repository.DeleteType
//   - opts ...search.Option
func (_e *NotificationTemplateRepository_Expecter) Delete(ctx interface{}, delType interface{}, opts ...interface{}) *NotificationTemplateRepository_Delete_Call {
	return &NotificationTemplateRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, delType}, opts...)...)}
}

func (_c *NotificationTemplateRepository_Delete_Call) Run(run func(ctx context.Context, delType repository.DeleteType, opts ...search.Option)) *NotificationTemplateRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), args[1].(repository.DeleteType), variadicArgs...)
	})
	return _c
}

func (_c *NotificationTemplateRepository_Delete_Call) Return(_a0 error) *NotificationTemplateRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationTemplateRepository_Delete_Call) RunAndReturn(run func(context.Context, repository.DeleteType, ...search.Option) error) *NotificationTemplateRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *NotificationTemplateRepository) Get(ctx context.Context, opts ...search.Option) (domain.NotificationTemplate, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.NotificationTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.NotificationTemplate, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.NotificationTemplate); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.NotificationTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationTemplateRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type NotificationTemplateRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *NotificationTemplateRepository_Expecter) Get(ctx interface{}, opts ...interface{}) *NotificationTemplateRepository_Get_Call {
	return &NotificationTemplateRepository_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *NotificationTemplateRepository_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *NotificationTemplateRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *NotificationTemplateRepository_Get_Call) Return(_a0 domain.NotificationTemplate, _a1 error) *NotificationTemplateRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationTemplateRepository_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.NotificationTemplate, error)) *NotificationTemplateRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetForRender provides a mock function with given fields: ctx, realmID, name, locale
func (_m *NotificationTemplateRepository) GetForRender(ctx context.Context, realmID string, name string, locale string) (domain.NotificationTemplate, error) {
	ret := _m.Called(ctx, realmID, name, locale)

	if len(ret) == 0 {
		panic("no return value specified for GetForRender")
	}

	var r0 domain.NotificationTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (domain.NotificationTemplate, error)); ok {
		return rf(ctx, realmID, name, locale)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) domain.NotificationTemplate); ok {
		r0 = rf(ctx, realmID, name, locale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.NotificationTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, realmID, name, locale)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationTemplateRepository_GetForRender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForRender'
type NotificationTemplateRepository_GetForRender_Call struct {
	*mock.Call
}

// GetForRender is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
//   - name string
//   - locale string
func (_e *NotificationTemplateRepository_Expecter) GetForRender(ctx interface{}, realmID interface{}, name interface{}, locale interface{}) *NotificationTemplateRepository_GetForRender_Call {
	return &NotificationTemplateRepository_GetForRender_Call{Call: _e.mock.On("GetForRender", ctx, realmID, name, locale)}
}

func (_c *NotificationTemplateRepository_GetForRender_Call) Run(run func(ctx context.Context, realmID string, name string, locale string)) *NotificationTemplateRepository_GetForRender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *NotificationTemplateRepository_GetForRender_Call) Return(_a0 domain.NotificationTemplate, _a1 error) *NotificationTemplateRepository_GetForRender_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationTemplateRepository_GetForRender_Call) RunAndReturn(run func(context.Context, string, string, string) (domain.NotificationTemplate, error)) *NotificationTemplateRepository_GetForRender_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *NotificationTemplateRepository) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.NotificationTemplate], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.NotificationTemplate]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.NotificationTemplate], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.NotificationTemplate]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.NotificationTemplate])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationTemplateRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type NotificationTemplateRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *NotificationTemplateRepository_Expecter) List(ctx interface{}, opts ...interface{}) *NotificationTemplateRepository_List_Call {
	return &NotificationTemplateRepository_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *NotificationTemplateRepository_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *NotificationTemplateRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *NotificationTemplateRepository_List_Call) Return(_a0 resource.ListResponse[domain.NotificationTemplate], _a1 error) *NotificationTemplateRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotificationTemplateRepository_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.NotificationTemplate], error)) *NotificationTemplateRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationTemplateRepository creates a new instance of NotificationTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationTemplateRepository {
	mock := &NotificationTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
