// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PreferenceUsecase is an autogenerated mock type for the PreferenceUsecase type
type PreferenceUsecase struct {
	mock.Mock
}

type PreferenceUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *PreferenceUsecase) EXPECT() *PreferenceUsecase_Expecter {
	return &PreferenceUsecase_Expecter{mock: &_m.Mock}
}

// Set provides a mock function with given fields: ctx, realmID, recipient, channel, suppressed
func (_m *PreferenceUsecase) Set(ctx context.Context, realmID string, recipient string, channel string, suppressed bool) error {
	ret := _m.Called(ctx, realmID, recipient, channel, suppressed)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) error); ok {
		r0 = rf(ctx, realmID, recipient, channel, suppressed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreferenceUsecase_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type PreferenceUsecase_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
//   - recipient string
//   - channel string
//   - suppressed bool
func (_e *PreferenceUsecase_Expecter) Set(ctx interface{}, realmID interface{}, recipient interface{}, channel interface{}, suppressed interface{}) *PreferenceUsecase_Set_Call {
	return &PreferenceUsecase_Set_Call{Call: _e.mock.On("Set", ctx, realmID, recipient, channel, suppressed)}
}

func (_c *PreferenceUsecase_Set_Call) Run(run func(ctx context.Context, realmID string, recipient string, channel string, suppressed bool)) *PreferenceUsecase_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *PreferenceUsecase_Set_Call) Return(_a0 error) *PreferenceUsecase_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PreferenceUsecase_Set_Call) RunAndReturn(run func(context.Context, string, string, string, bool) error) *PreferenceUsecase_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewPreferenceUsecase creates a new instance of PreferenceUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreferenceUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreferenceUsecase {
	mock := &PreferenceUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
