// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	domain "github.com/fromforgesoftware/gjallarhorn/internal/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/fromforgesoftware/go-kit/application/repository"

	resource "github.com/fromforgesoftware/go-kit/resource"

	search "github.com/fromforgesoftware/go-kit/search"
)

// TemplateUsecase is an autogenerated mock type for the TemplateUsecase type
type TemplateUsecase struct {
	mock.Mock
}

type TemplateUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *TemplateUsecase) EXPECT() *TemplateUsecase_Expecter {
	return &TemplateUsecase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, t
func (_m *TemplateUsecase) Create(ctx context.Context, t domain.NotificationTemplate) (domain.NotificationTemplate, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.NotificationTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.NotificationTemplate) (domain.NotificationTemplate, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.NotificationTemplate) domain.NotificationTemplate); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.NotificationTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.NotificationTemplate) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TemplateUsecase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TemplateUsecase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t domain.NotificationTemplate
func (_e *TemplateUsecase_Expecter) Create(ctx interface{}, t interface{}) *TemplateUsecase_Create_Call {
	return &TemplateUsecase_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *TemplateUsecase_Create_Call) Run(run func(ctx context.Context, t domain.NotificationTemplate)) *TemplateUsecase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.NotificationTemplate))
	})
	return _c
}

func (_c *TemplateUsecase_Create_Call) Return(_a0 domain.NotificationTemplate, _a1 error) *TemplateUsecase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TemplateUsecase_Create_Call) RunAndReturn(run func(context.Context, domain.NotificationTemplate) (domain.NotificationTemplate, error)) *TemplateUsecase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, delType, opts
func (_m *TemplateUsecase) Delete(ctx context.Context, delType repository.DeleteType, opts ...search.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, delType)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteType, ...search.Option) error); ok {
		r0 = rf(ctx, delType, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TemplateUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TemplateUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - delType repository.DeleteType
//   - opts ...search.Option
func (_e *TemplateUsecase_Expecter) Delete(ctx interface{}, delType interface{}, opts ...interface{}) *TemplateUsecase_Delete_Call {
	return &TemplateUsecase_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, delType}, opts...)...)}
}

func (_c *TemplateUsecase_Delete_Call) Run(run func(ctx context.Context, delType repository.DeleteType, opts ...search.Option)) *TemplateUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), args[1].(repository.DeleteType), variadicArgs...)
	})
	return _c
}

func (_c *TemplateUsecase_Delete_Call) Return(_a0 error) *TemplateUsecase_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TemplateUsecase_Delete_Call) RunAndReturn(run func(context.Context, repository.DeleteType, ...search.Option) error) *TemplateUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, opts
func (_m *TemplateUsecase) Get(ctx context.Context, opts ...search.Option) (domain.NotificationTemplate, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.NotificationTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (domain.NotificationTemplate, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) domain.NotificationTemplate); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.NotificationTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TemplateUsecase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TemplateUsecase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *TemplateUsecase_Expecter) Get(ctx interface{}, opts ...interface{}) *TemplateUsecase_Get_Call {
	return &TemplateUsecase_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *TemplateUsecase_Get_Call) Run(run func(ctx context.Context, opts ...search.Option)) *TemplateUsecase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *TemplateUsecase_Get_Call) Return(_a0 domain.NotificationTemplate, _a1 error) *TemplateUsecase_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TemplateUsecase_Get_Call) RunAndReturn(run func(context.Context, ...search.Option) (domain.NotificationTemplate, error)) *TemplateUsecase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *TemplateUsecase) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[domain.NotificationTemplate], error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[domain.NotificationTemplate]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[domain.NotificationTemplate], error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[domain.NotificationTemplate]); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[domain.NotificationTemplate])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TemplateUsecase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TemplateUsecase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *TemplateUsecase_Expecter) List(ctx interface{}, opts ...interface{}) *TemplateUsecase_List_Call {
	return &TemplateUsecase_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *TemplateUsecase_List_Call) Run(run func(ctx context.Context, opts ...search.Option)) *TemplateUsecase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *TemplateUsecase_List_Call) Return(_a0 resource.ListResponse[domain.NotificationTemplate], _a1 error) *TemplateUsecase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TemplateUsecase_List_Call) RunAndReturn(run func(context.Context, ...search.Option) (resource.ListResponse[domain.NotificationTemplate], error)) *TemplateUsecase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Render provides a mock function with given fields: ctx, realmID, name, locale, data
func (_m *TemplateUsecase) Render(ctx context.Context, realmID string, name string, locale string, data map[string]interface{}) (string, string, error) {
	ret := _m.Called(ctx, realmID, name, locale, data)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]interface{}) (string, string, error)); ok {
		return rf(ctx, realmID, name, locale, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]interface{}) string); ok {
		r0 = rf(ctx, realmID, name, locale, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, map[string]interface{}) string); ok {
		r1 = rf(ctx, realmID, name, locale, data)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, map[string]interface{}) error); ok {
		r2 = rf(ctx, realmID, name, locale, data)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TemplateUsecase_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type TemplateUsecase_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
//   - name string
//   - locale string
//   - data map[string]interface{}
func (_e *TemplateUsecase_Expecter) Render(ctx interface{}, realmID interface{}, name interface{}, locale interface{}, data interface{}) *TemplateUsecase_Render_Call {
	return &TemplateUsecase_Render_Call{Call: _e.mock.On("Render", ctx, realmID, name, locale, data)}
}

func (_c *TemplateUsecase_Render_Call) Run(run func(ctx context.Context, realmID string, name string, locale string, data map[string]interface{})) *TemplateUsecase_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(map[string]interface{}))
	})
	return _c
}

func (_c *TemplateUsecase_Render_Call) Return(subject string, body string, err error) *TemplateUsecase_Render_Call {
	_c.Call.Return(subject, body, err)
	return _c
}

func (_c *TemplateUsecase_Render_Call) RunAndReturn(run func(context.Context, string, string, string, map[string]interface{}) (string, string, error)) *TemplateUsecase_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewTemplateUsecase creates a new instance of TemplateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateUsecase {
	mock := &TemplateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
