// Code generated by mockery. DO NOT EDIT.

package apptest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TemplateRenderer is an autogenerated mock type for the TemplateRenderer type
type TemplateRenderer struct {
	mock.Mock
}

type TemplateRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *TemplateRenderer) EXPECT() *TemplateRenderer_Expecter {
	return &TemplateRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function with given fields: ctx, realmID, name, locale, data
func (_m *TemplateRenderer) Render(ctx context.Context, realmID string, name string, locale string, data map[string]interface{}) (string, string, error) {
	ret := _m.Called(ctx, realmID, name, locale, data)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]interface{}) (string, string, error)); ok {
		return rf(ctx, realmID, name, locale, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]interface{}) string); ok {
		r0 = rf(ctx, realmID, name, locale, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, map[string]interface{}) string); ok {
		r1 = rf(ctx, realmID, name, locale, data)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, map[string]interface{}) error); ok {
		r2 = rf(ctx, realmID, name, locale, data)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TemplateRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type TemplateRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - ctx context.Context
//   - realmID string
//   - name string
//   - locale string
//   - data map[string]interface{}
func (_e *TemplateRenderer_Expecter) Render(ctx interface{}, realmID interface{}, name interface{}, locale interface{}, data interface{}) *TemplateRenderer_Render_Call {
	return &TemplateRenderer_Render_Call{Call: _e.mock.On("Render", ctx, realmID, name, locale, data)}
}

func (_c *TemplateRenderer_Render_Call) Run(run func(ctx context.Context, realmID string, name string, locale string, data map[string]interface{})) *TemplateRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(map[string]interface{}))
	})
	return _c
}

func (_c *TemplateRenderer_Render_Call) Return(subject string, body string, err error) *TemplateRenderer_Render_Call {
	_c.Call.Return(subject, body, err)
	return _c
}

func (_c *TemplateRenderer_Render_Call) RunAndReturn(run func(context.Context, string, string, string, map[string]interface{}) (string, string, error)) *TemplateRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewTemplateRenderer creates a new instance of TemplateRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateRenderer {
	mock := &TemplateRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
